name: PRP CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Check Python Code
        run: python -m py_compile app.py

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/arunvignesh135/prp-job-portal:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/arunvignesh135/prp-job-portal:latest
        
              - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/prp-job-portal
            ./deploy.sh
       
